name: fluttermvvmtemplate
description: A Flutter template project for everyone.

publish_to: none 

version: 0.0.9

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: ^2.2.0
  mobx: ^2.2.1
  provider: ^6.1.1
  

   # database
  shared_preferences: ^2.2.2

  #singleton
  get_it: ^7.6.4
  # firebase
  # firebase_core: ^2.1.1
  # firebase_analytics: ^10.7.1

  # coffing 
  json_annotation: ^4.8.1
  # envied: ^0.5.2
  #Navigation
  auto_route: ^7.8.4
  # language
  easy_localization: ^3.0.3

  #utility
  easy_logger: ^0.0.2
  # network    
  vexana: ^3.5.2
  
  
  # core utilities
  kartal: ^3.5.0
  logger: ^2.0.2+1
  webview_flutter: ^4.4.2
  equatable: ^2.0.5

  # ui utilities
  animations: ^2.0.0
  auto_size_text: ^3.0.0
  
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0

  gen:
    path: module/gen


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  # envied_generator: ^0.5.2
  pubspec_dependency_sorter: ^1.0.4
  auto_route_generator: ^7.3.2
  # flutter_gen_runner: ^5.3.2
  
flutter:
  uses-material-design: true

  assets:
    - module/gen/asset/lang/
    - module/gen/asset/svg/
    